# -*- coding: utf-8 -*-
"""dlpractical_exam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKDmw7HAei5gCjkA49tPbayFqjB7qyTe
"""

# ==========================================
# 🧠 Brain Tumor Classification (ResNet50)
# Single File - Google Colab Ready
# ==========================================

# 🔹 STEP 1: Install Required Libraries
!pip install -q tensorflow scikit-learn

# 🔹 STEP 2: Import Libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import zipfile
import io

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import load_img, img_to_array
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import confusion_matrix, classification_report

# 🔹 STEP 3: Upload ZIP Dataset
from google.colab import files
uploaded = files.upload()

# 🔹 STEP 4: Extract Dataset
for file in uploaded.keys():
    with zipfile.ZipFile(io.BytesIO(uploaded[file]), 'r') as zip_ref:
        zip_ref.extractall('/content/dataset')

# 🔹 STEP 5: Check Folder Structure
print("\nDataset Structure:\n")
for root, dirs, files in os.walk('/content/dataset'):
    print(root)

# 🔹 STEP 6: Set Correct Path (EDIT IF NEEDED)
data_dir = "/content/dataset/data"

# 👉 If you see an extra folder like brain_tumor_dataset, use:
# data_dir = "/content/dataset/brain_tumor_dataset"

# 🔹 STEP 7: Data Preprocessing
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

# 🔹 STEP 8: Load Pre-trained ResNet50
base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze layers
for layer in base_model.layers:
    layer.trainable = False

# 🔹 STEP 9: Build Model
model = Sequential([
    base_model,
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(4, activation='softmax')
])

# 🔹 STEP 10: Compile Model
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 🔹 STEP 11: Train Model
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

# 🔹 STEP 12: Plot Accuracy
plt.figure()
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Model Accuracy")
plt.show()

# 🔹 STEP 13: Evaluate Model
Y_pred = model.predict(val_data)
y_pred = np.argmax(Y_pred, axis=1)

cm = confusion_matrix(val_data.classes, y_pred)
print("\nConfusion Matrix:\n", cm)

print("\nClassification Report:\n")
print(classification_report(val_data.classes, y_pred))

# 🔹 STEP 14: Sensitivity & Specificity
TP = np.diag(cm)
FN = np.sum(cm, axis=1) - TP
FP = np.sum(cm, axis=0) - TP
TN = np.sum(cm) - (FP + FN + TP)

sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)

print("\nSensitivity:", sensitivity)
print("Specificity:", specificity)

# 🔹 STEP 15: Save Model
model.save("/content/brain_tumor_model.h5")
print("\nModel saved successfully!")

# 🔹 STEP 16: Prediction Function
def predict_image(img_path):
    img = load_img(img_path, target_size=(224, 224))
    img_array = img_to_array(img)/255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    classes = list(train_data.class_indices.keys())

    print("\nPrediction:", classes[np.argmax(prediction)])

# 👉 Example usage:
# Upload a test image and run:
# predict_image('/content/your_image.jpg')

# ==========================================
# 📂 Select Image from File Picker & Predict
# ==========================================

from google.colab import files
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
import matplotlib.pyplot as plt

def select_and_predict():
    print("📂 Please select an MRI image...")

    uploaded = files.upload()   # Opens file picker

    for file_name in uploaded.keys():

        # 🔹 Display Image
        img = load_img(file_name, target_size=(224, 224))
        plt.imshow(img)
        plt.title("Selected Image")
        plt.axis('off')
        plt.show()

        # 🔹 Preprocess Image
        img_array = img_to_array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        # 🔹 Predict
        prediction = model.predict(img_array)[0] # Get the first (and only) prediction from the batch
        classes = list(train_data.class_indices.keys())

        # Create a list of (class_name, probability) tuples
        class_probabilities = []
        for i, prob in enumerate(prediction):
            class_probabilities.append((classes[i], prob))

        # Sort by probability in descending order
        class_probabilities.sort(key=lambda x: x[1], reverse=True)

        # 🔹 Output
        print("\n==============================")
        print("🧠 Brain Tumor Detection Result")
        print("==============================")
        for class_name, prob in class_probabilities:
            print(f"{class_name.ljust(15)} : {prob*100:.2f}%")
        print("==============================")
        print("\nNote: The model's validation accuracy was around 40-45%.")
        print("This means predictions may not always be highly reliable.")

select_and_predict()